@startuml MedComAcknowledgementMessage

hide empty members

class "MedComAcknowledgementMessage" as message <<MedComMessagingMessage>>
class "MedComAcknowledgementMessageHeader" as messageHeader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as organization <<MedComCoreOrganization>>
class "MedComMessagingProvenance" as provenance
class "MedComAcknowledgementOperationOutcome" as outcome

message --> messageHeader : "entry"
message --> provenance : "entry"
provenance --> messageHeader : "target"
provenance --> organization : "agent.who"

messageHeader --> organization : "sender"
messageHeader --> organization : "receiver"
messageHeader --> outcome : "response.details"
@enduml
